### PR TITLE
Split up and overhaul generation scripts

### PR DESCRIPTION
**Pull request by DavidFair**
- Chunk major steps into separate componenets
- Introduce data classes instead of lists
- Rejig loops / os.path usage to pathlib
- Add tests with pytest
- Update Jinja to understand new data structs
- Drop Paraview support / mentions (these were only lists for 3.3)
- Add venv instructions

**To test**
- Follow instructions on README
- Check the generated pages match our [existing ones](https://download.mantidproject.org)

### CODE REVIEW

**Comment by DavidFair** [comment]
@DanielMurphy22 @martyngigg 
Could you both have a look at this, because it's such a large change I think it's worth 2 reviewers

**Review by DanielMurphy22 — COMMENTED** [review]
(tested on Ubuntu) Seems to work well for me, just address the conflict!

I'd like to note that the installation instructions pages have lots of mentions of MantidPlot, and the font change at the bottom of the docker page is a little odd. It also looks like a previous change on main of this repo (to add the apt-get / yum comment to the top of the index.html page) hasn't been updated on the online docs. Is updating the online downloads page a manual process??

Also, I used `conda` instead of `mamba` in following the README instructions.

**Review by martyngigg — CHANGES_REQUESTED** [review]
This looks much cleaner and thanks for adding the tests!

Just one thing I spotted: there seems to be 2 OSX links in the nightly section? I just ran the buildscript - did I do something wrong?

Screenshot 2022-01-31 at 09 43 16

**Comment by DavidFair** [comment]
It looks like a 5.1 nightly is lingering around: https://github.com/mantidproject/download.mantidproject.org/blob/main/releases/nightly.txt#L1

So I guess this is more true to displaying everything in the file rather than it silently fixing bugs elsewhere.
Let me have a look to see where this file is coming from, but AFAIK it's not a problem with this PR...

**Comment by DavidFair** [comment]
@martyngigg Any idea where `nightly.txt` gets populated from, I can't seem to see the Job or script?

**Comment by martyngigg** [comment]
It's currently created inside https://builds.mantidproject.org/view/Main%20Pipeline/job/main_deploy/configure in one of the legacy jobs using the web interface. The `create-manifest` script does the job.

Perhaps we would be better moving the custom release/*.txt files to a single `.json` that would be easier to parse and regenerate?

**Comment by DavidFair** [comment]
> It's currently created inside https://builds.mantidproject.org/view/Main%20Pipeline/job/main_deploy/configure in one of the legacy jobs using the web interface. The `create-manifest` script does the job.

I can't see it on the production server, so I'm manually going to remove the line and see if it reappears :thinking: 

> Perhaps we would be better moving the custom release/*.txt files to a single `.json` that would be easier to parse and regenerate?

:+1:  but I would do it as a separate PR as we need to move the job script out of Jenkins and into our source control beforehand too

**Comment by martyngigg** [comment]
> > It's currently created inside https://builds.mantidproject.org/view/Main%20Pipeline/job/main_deploy/configure in one of the legacy jobs using the web interface. The `create-manifest` script does the job.
> 
> I can't see it on the production server, so I'm manually going to remove the line and see if it reappears 🤔
> 
> > Perhaps we would be better moving the custom release/*.txt files to a single `.json` that would be easier to parse and regenerate?
> 
> 👍 but I would do it as a separate PR as we need to move the job script out of Jenkins and into our source control beforehand too

Yeah that's definintely a separate issue. I just wanted to raise it here while I thought of it as it will make maintaining those scripts easier.

**Review by martyngigg — APPROVED** [review]
Confirmed the rogue nightly no longer causes issues.

**Pull request merged**
